/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Value = {
  lines?: Array<string>;
};

export type OwnershipValue = {
  holder?: string;
  percent?: number;
  jvPartner?: string;
  jvTerms?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Image1 = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: 'image';
};

export type PersonReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'person';
};

export type LegalPage = {
  _id: string;
  _type: 'legalPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: 'disclaimer' | 'privacy' | 'terms';
  lastUpdated?: FactDate;
  clauses?: Array<
    {
      _key: string;
    } & LegalClause
  >;
  clausesBrief?: string;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  approvedBy?: PersonReference;
  approvedAt?: string;
};

export type FactDate = {
  _type: 'factDate';
  value?: string;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?:
    | 'company'
    | 'leadership'
    | 'howWeExplore'
    | 'investors'
    | 'announcements'
    | 'reports'
    | 'presentations'
    | 'shareholders'
    | 'governance'
    | 'alerts'
    | 'sustainability'
    | 'community'
    | 'environmentSafety'
    | 'news'
    | 'media'
    | 'contact';
  intro?: Narrative;
  sections?: Array<
    {
      _key: string;
    } & PageSection
  >;
};

export type Narrative = {
  _type: 'narrative';
  text?: string;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  approvedBy?: PersonReference;
  approvedAt?: string;
  brief?: string;
};

export type PortfolioPage = {
  _id: string;
  _type: 'portfolioPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro?: Narrative;
  portfolioMap?: FigureSlot;
};

export type FigureReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'figure';
};

export type FigureSlot = {
  _type: 'figureSlot';
  figure?: FigureReference;
  brief?: string;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading?: Narrative;
  heroIntro?: Narrative;
  portfolioMap?: FigureSlot;
  whyHeading?: Narrative;
  whyText?: Interpretation;
  crossSection?: FigureSlot;
  sustainabilityLine?: Narrative;
};

export type DocumentRecordReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'documentRecord';
};

export type Interpretation = {
  _type: 'interpretation';
  text?: string;
  sources?: Array<
    {
      _key: string;
    } & DocumentRecordReference
  >;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  asAt?: string;
  reviewedBy?: PersonReference;
  note?: string;
  brief?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'project';
};

export type Article = {
  _id: string;
  _type: 'article';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  slug?: Slug;
  date?: FactDate;
  lead?: Narrative;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  approvedBy?: PersonReference;
  approvedAt?: string;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  linkedDocument?: DocumentRecordReference;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type WorkItem = {
  _id: string;
  _type: 'workItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  project?: ProjectReference;
  method?: string;
  quantity?: FactNumber;
  year?: FactNumber;
  operator?: FactOperator;
};

export type FactOperator = {
  _type: 'factOperator';
  value?: 'auburn' | 'historic';
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type FactNumber = {
  _type: 'factNumber';
  value?: number;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type Milestone = {
  _id: string;
  _type: 'milestone';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  project?: ProjectReference;
  title?: string;
  state?: 'done' | 'next' | 'planned';
  when?: FactString;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  approvedBy?: PersonReference;
  approvedAt?: string;
};

export type FactString = {
  _type: 'factString';
  value?: string;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type Result = {
  _id: string;
  _type: 'result';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  project?: ProjectReference;
  headline?: FactString;
  holeOrSurveyId?: FactString;
  prospectName?: string;
  reportedIn?: DocumentRecordReference;
};

export type ResourceEstimate = {
  _id: string;
  _type: 'resourceEstimate';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  project?: ProjectReference;
  category?: FactString;
  tonnesMt?: FactNumber;
  grades?: FactString;
  containedMetal?: FactString;
  cutOff?: FactString;
  estimateDate?: FactDate;
};

export type Prospect = {
  _id: string;
  _type: 'prospect';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  project?: ProjectReference;
  name?: string;
  summary?: Interpretation;
  targetType?: FactString;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  name?: string;
  slug?: Slug;
  sheetNumber?: string;
  holding?: FactHolding;
  state?: FactState;
  commodities?: FactCommodities;
  stage?: FactStage;
  areaKm2?: FactNumber;
  ownership?: FactOwnership;
  heroThesis?: Narrative;
  geologySummary?: Interpretation;
  statements?: Array<
    {
      _key: string;
    } & Interpretation
  >;
  tenements?: FactString;
  asAt?: FactDate;
  setting?: ProjectSetting;
  heroPhoto?: PhotoSlot;
  settingMap?: FigureSlot;
  sectionFigure?: FigureSlot;
  photos?: Array<
    {
      _key: string;
    } & PhotoSlot
  >;
  cpStatement?: Interpretation;
  heldBackNote?: string;
  legacyPath?: string;
};

export type PhotoReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'photo';
};

export type PhotoSlot = {
  _type: 'photoSlot';
  photo?: PhotoReference;
  brief?: string;
};

export type ProjectSetting = {
  _type: 'projectSetting';
  neighbouringDeposits?: FactString;
  nearestTown?: FactString;
  access?: FactString;
  infrastructure?: FactString;
  traditionalOwners?: FactString;
};

export type FactOwnership = {
  _type: 'factOwnership';
  value?: OwnershipValue;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type FactStage = {
  _type: 'factStage';
  value?: 'targetGeneration' | 'drillReady' | 'drilling' | 'resourceDefinition';
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type FactCommodities = {
  _type: 'factCommodities';
  value?: Array<string>;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type FactState = {
  _type: 'factState';
  value?: 'QLD' | 'NT';
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type FactHolding = {
  _type: 'factHolding';
  value?: 'active' | 'underReview' | 'noLongerHeld';
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  legalName?: FactString;
  companyType?: FactString;
  acn?: FactString;
  abn?: FactString;
  phone?: FactString;
  email?: FactString;
  streetAddress?: FactAddress;
  postalAddress?: FactAddress;
  socialProfiles?: FactStringList;
  acknowledgementOfCountry?: Narrative;
  keyFacts?: KeyFacts;
};

export type KeyFacts = {
  _type: 'keyFacts';
  projectCount?: FactNumber;
  flagshipCount?: FactNumber;
  groundHeld?: FactNumber;
  commodities?: FactCommodities;
  jurisdictions?: FactStates;
  companyStatus?: FactString;
  dgrHolding?: FactNumber;
  sharesOnIssue?: FactNumber;
  ipoStatus?: FactString;
};

export type FactStringList = {
  _type: 'factStringList';
  value?: Array<string>;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type FactAddress = {
  _type: 'factAddress';
  value?: Value;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type LegalClause = {
  _type: 'legalClause';
  heading?: string;
  text?: Interpretation;
};

export type PageSection = {
  _type: 'pageSection';
  sectionId?: string;
  heading?: string;
  paragraphs?: Array<
    | ({
        _key: string;
      } & Narrative)
    | ({
        _key: string;
      } & Interpretation)
  >;
  forwardLooking?: boolean;
};

export type FactStates = {
  _type: 'factStates';
  value?: Array<string>;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type Photo = {
  _id: string;
  _type: 'photo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: Image1;
  caption?: string;
  alt?: string;
  longDescription?: string;
  source?: string;
  date?: string;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  approvedBy?: PersonReference;
  approvedAt?: string;
  place?: string;
  photographer?: string;
  consentNote?: string;
};

export type Figure = {
  _id: string;
  _type: 'figure';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  figureType?: 'map' | 'section' | 'geophysics' | 'other';
  image?: Image1;
  caption?: string;
  alt?: string;
  longDescription?: string;
  source?: string;
  date?: string;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  approvedBy?: PersonReference;
  approvedAt?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type FactMeta = {
  _type: 'factMeta';
  sourceDocument?: DocumentRecordReference;
  asAt?: string;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  approvedBy?: PersonReference;
  approvedAt?: string;
  reviewBy?: string;
  note?: string;
};

export type FactBoolean = {
  _type: 'factBoolean';
  value?: boolean;
  unit?: string;
  qualifier?: string;
  brief?: string;
  meta?: FactMeta;
};

export type DocumentRecord = {
  _id: string;
  _type: 'documentRecord';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  title?: string;
  slug?: Slug;
  ref?: FactString;
  docType?:
    | 'announcement'
    | 'quarterly'
    | 'halfYear'
    | 'annual'
    | 'presentation'
    | 'policy'
    | 'notice'
    | 'sourceCapture'
    | 'thirdParty'
    | 'other';
  releaseAt?: FactDate;
  status?: 'draft' | 'toVerify' | 'approved' | 'superseded';
  approvedBy?: PersonReference;
  approvedAt?: string;
  internal?: boolean;
  summary?: Narrative;
  file?: FactString;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  externalUrl?: string;
  legacyPath?: string;
  note?: string;
};

export type Person = {
  _id: string;
  _type: 'person';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  order?: number;
  name?: string;
  group?: 'board' | 'management';
  role?: FactString;
  bio?: Interpretation;
  qualifications?: FactString;
  portrait?: FactString;
  cpMembership?: FactString;
  cpConsent?: FactBoolean;
  approverFor?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Value
  | OwnershipValue
  | SanityImageAssetReference
  | Image1
  | PersonReference
  | LegalPage
  | FactDate
  | Page
  | Narrative
  | PortfolioPage
  | FigureReference
  | FigureSlot
  | HomePage
  | DocumentRecordReference
  | Interpretation
  | ProjectReference
  | Article
  | Slug
  | WorkItem
  | FactOperator
  | FactNumber
  | Milestone
  | FactString
  | Result
  | ResourceEstimate
  | Prospect
  | Project
  | PhotoReference
  | PhotoSlot
  | ProjectSetting
  | FactOwnership
  | FactStage
  | FactCommodities
  | FactState
  | FactHolding
  | SiteSettings
  | KeyFacts
  | FactStringList
  | FactAddress
  | LegalClause
  | PageSection
  | FactStates
  | Photo
  | Figure
  | SanityImageCrop
  | SanityImageHotspot
  | FactMeta
  | FactBoolean
  | DocumentRecord
  | Person
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
